
services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inorbit
    volumes:
      - ./docker:/docker-entrypoint-initdb.d

