name: Run backend tests
on:
  push:
    paths:
      - 'server/**'

jobs:
  run-ci:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inorbit_test
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all branches
        run: git fetch --prune --unshallow

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Check if package-lock.json exists
        run: |
          if [ ! -f "server/package-lock.json" ]; then
            echo "Error: package-lock.json not found in server/ directory!"
            exit 1
          fi

      - name: Install dependencies
        run: |
          cd server
          npm ci

      - name: Run tests
        run: |
          cd server
          npm test
